#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "neoengineer"
git config --global user.email thomas.may@msepros.com
